package handlers;

public enum Endpoint {
    GET_TASKS, GET_TASK_BY_ID, CREATE_TASK, UPDATE_TASK, DELETE_TASK,
    GET_SUBTASKS, GET_SUBTASK_BY_ID, CREATE_SUBTASK, UPDATE_SUBTASK, DELETE_SUBTASK,
    GET_EPICS, GET_EPIC_BY_ID, CREATE_EPIC, DELETE_EPIC, GET_SUBTASKS_IN_EPIC,
    GET_HISTORY,
    GET_PRIORITIZED_TASKS,
    UNKNOWN
}
